import { afterEach, beforeEach, expect, it } from "vitest";
import { duckglueAdapter } from "../src/semantic/duckglue.ts";
import { openStore, closeStore, initializeCoreLibrary, saveDashboard, loadDashboard, listCoreLibrary, updateLibraryItem, saveLibraryFolder, deleteLibraryFolder, deleteDashboard, exportLibrary, restoreLibrary, listDashboards } from "../src/store/store.ts";
import { libraryStarters } from "../src/library/setup.ts";
import { model as otherModel } from "./fixtures.ts";
const scope = { source: "sample", model: "sample" };
beforeEach(() => openStore(":memory:")); afterEach(closeStore);
const sample = async () => (await duckglueAdapter.load("sample-data/warehouse.yaml"))!;
it("files existing work without changing content, creates validated starters, and opens copies without overwriting templates", async () => {
  const model = await sample(), starters = libraryStarters(model);
  expect(starters).toHaveLength(9);
  const spec = { ...starters[0].spec, title: "My monthly report" };
  await saveDashboard({ id: "mine", spec }, scope);
  await saveLibraryFolder({ id: "custom", name: "Already organized" }, scope);
  await saveDashboard({ id: "filed", spec, folderId: "custom" }, scope);
  await initializeCoreLibrary(scope, model);
  const library = await listCoreLibrary(scope);
  expect(library.folders.filter(f => !f.parentId).map(f => f.name)).toEqual(["Company overview", "Revenue & retention", "Growth & customers", "Shared views", "Examples", "Already organized"]);
  const mine = (await loadDashboard("mine", scope))!;
  expect(mine.spec).toEqual(spec); expect(mine.revision).toBe(2);
  expect(mine.folderId).toBe(library.folders.find(f => f.name === "Company overview")?.id);
  expect((await loadDashboard("filed", scope))?.folderId).toBe("custom");
  expect((await listDashboards(scope)).map(d => d.id).sort()).toEqual(["filed", "mine"]);
  const starter = library.items.find(i => i.isTemplate)!;
  const source = (await loadDashboard(starter.id, scope))!;
  const { isTemplate: _, ...document } = source;
  await expect(saveDashboard({ ...document, revision: 1 }, scope)).rejects.toThrow(/starter/);
  await saveDashboard({ ...document, id: "copy", revision: 0 }, scope);
  expect((await loadDashboard("copy", scope))?.isTemplate).toBe(false);
  expect((await loadDashboard(starter.id, scope))?.revision).toBe(1);
  expect((await listCoreLibrary({ ...scope, source: "other" })).items).toHaveLength(0);
});
it("preserves organization and removals through initialization, backup, and restore", async () => {
  const model = await sample(); await initializeCoreLibrary(scope, model);
  const library = await listCoreLibrary(scope), example = library.items.find(i => i.name === "Dashboard cleanup demo")!;
  await deleteDashboard(example.id, scope, example.revision);
  await deleteLibraryFolder(example.folderId!, 1, scope);
  const folder = library.folders.find(f => f.name === "Company overview")!;
  await saveLibraryFolder({ ...folder, name: "Leadership" }, scope);
  const starter = library.items.find(i => i.name === "MRR movements")!;
  await updateLibraryItem("dashboard", starter.id, { revision: starter.revision, folderId: folder.id }, scope);
  await initializeCoreLibrary(scope, model);
  const backup = await exportLibrary();
  await closeStore(); await openStore(":memory:"); await restoreLibrary(backup);
  await initializeCoreLibrary(scope, model);
  const restored = await exportLibrary();
  expect(restored.dashboards).toEqual(backup.dashboards); expect(restored.folders).toEqual(backup.folders);
  expect(restored.initializedSources).toEqual([scope.source]);
  expect((await listCoreLibrary(scope)).folders.some(f => f.name === "Examples")).toBe(false);
});
it("does not fabricate sample dashboards for an unrelated semantic catalogue", async () => {
  await initializeCoreLibrary(scope, otherModel);
  const library = await listCoreLibrary(scope); expect(library.items).toEqual([]); expect(library.folders).toHaveLength(8);
});
