import { expect, it } from "vitest";
import { PDFDocument } from "pdf-lib";
import { model } from "./fixtures.ts";
import { blueprintSchema, buildReference, initialMapping, metricMatches, type Blueprint } from "../src/reference/blueprint.ts";
import { validateReferenceUpload } from "../src/reference/analyze.ts";
const blueprint = (): Blueprint => ({ title: "A sketch", pages: [{ title: "Overview", aspectRatio: 1.5, items: [{ id: "revenue", kind: "metric", label: "Revenue", metrics: ["Revenue (USD)"], dimensions: ["country"], grain: "none", chart: "bar", x: 0, y: 0.1, w: 0.5, h: 0.4 }] }] });
it("matches unique labels and synonyms, leaving ambiguous labels unresolved", () => {
  expect(metricMatches(model, "sales")).toEqual(["revenue"]); const changed = structuredClone(model); changed.metrics.live_revenue.synonyms.push("sales"); expect(metricMatches(changed, "sales")).toHaveLength(2);
  const b = blueprint(); b.pages[0].items[0].metrics = ["sales"]; expect(initialMapping(b, changed)["revenue:m0"]).toBe("");
});
it("recreates matched charts using catalogue names and reference positions", () => { const b = blueprint(), plan = buildReference(b, initialMapping(b, model), model); expect(plan.spec.tiles[0].metrics).toEqual(["revenue"]); expect(plan.spec.tiles[0].dimensions).toEqual(["dim_users.country"]); expect(plan.spec.tiles[0].layout.x).toBe(24); expect(plan.notes[0].status).toBe("ready"); });
it("keeps missing metrics and incompatible dimensions as explicit placeholders", () => { const b = blueprint(); b.pages[0].items[0].metrics = ["Profit forecast"]; const plan = buildReference(b, initialMapping(b, model), model); expect(plan.spec.tiles[0].kind).toBe("text"); expect(plan.spec.tiles[0].metrics).toEqual([]); expect(plan.notes[0].status).toBe("unresolved"); });
it("reveals required native-grain adjustments and rejects incompatible grains", () => { const m = structuredClone(model); m.metrics.revenue.timeGrains = ["month"]; m.metrics.revenue.timeDimension = "fct_sales.sold_on"; const b = blueprint(); b.pages[0].items[0].dimensions = []; const plan = buildReference(b, initialMapping(b, m), m); expect(plan.notes[0].status).toBe("adjusted"); expect(plan.spec.tiles[0].dimensions).toEqual(["month:fct_sales.sold_on"]); b.pages[0].items[0].dimensions = ["fct_sales.sold_on"]; b.pages[0].items[0].grain = "year"; expect(buildReference(b, initialMapping(b, m), m).notes[0].status).toBe("unresolved"); });
it("makes each PDF page a tab and connects recognized filters on that page", () => { const b = blueprint(); b.pages[0].items.push({ ...b.pages[0].items[0], id: "filter", kind: "filter", label: "Country", metrics: [] }); b.pages.push({ ...b.pages[0], title: "Detail", items: [{ ...b.pages[0].items[0], id: "detail" }] }); const plan = buildReference(b, initialMapping(b, model), model); expect(plan.spec.tabs).toHaveLength(2); expect(plan.spec.filters![0].bindings.map(b => b.tileId)).toEqual(["reference-revenue"]); });
it("rejects duplicate IDs, invalid geometry and excessive pages", () => { const b = blueprint(); b.pages[0].items.push(b.pages[0].items[0]); expect(blueprintSchema.safeParse(b).success).toBe(false); b.pages[0].items.pop(); b.pages[0].items[0].x = -1; expect(blueprintSchema.safeParse(b).success).toBe(false); });
it("validates PDF magic, readability and page limits before any AI call", async () => { const pdf = await PDFDocument.create(); pdf.addPage(); const data = Buffer.from(await pdf.save()).toString("base64"); expect((await validateReferenceUpload({ mime: "application/pdf", data })).pages).toBe(1); for (let i = 0; i < 6; i++) pdf.addPage(); await expect(validateReferenceUpload({ mime: "application/pdf", data: Buffer.from(await pdf.save()).toString("base64") })).rejects.toThrow("1–6"); await expect(validateReferenceUpload({ mime: "image/png", data })).rejects.toThrow("contents"); await expect(validateReferenceUpload({ mime: "application/pdf", data: Buffer.from("%PDF-broken garbage").toString("base64") })).rejects.toThrow("could not be read"); });
