import { expect, test } from "@playwright/test";

test("chart comments survive reopening, replies resolve, and personal alerts keep a quiet history", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/");
  await page.getByRole("button", { name: "Messy dashboard", exact: true }).click();
  await page.getByLabel("Acting as", { exact: true }).selectOption("admin");
  // The rough draft intentionally overlaps. Arrange first so the controls are usable.
  await page.getByRole("button", { name: "Smart arrange", exact: true }).click();
  await page.getByRole("button", { name: "Apply layout", exact: true }).click();
  const comments = page.getByRole("button", { name: /^Chart comments/ }).first();
  await comments.click();
  const drawer = page.getByRole("dialog");
  await expect(drawer.getByText("Give this chart a home")).toBeVisible();
  await drawer.getByRole("button", { name: "Save dashboard", exact: true }).click();
  await expect(drawer.getByLabel("Add to the conversation")).toBeEnabled();
  await drawer.getByLabel("Add to the conversation").fill("Revenue deserves a little context. <b>This is plain text.</b>");
  await drawer.getByRole("button", { name: "Post comment", exact: true }).click();
  await expect(drawer.locator(".activity-message")).toHaveText("Revenue deserves a little context. <b>This is plain text.</b>");
  await expect(drawer.locator(".activity-message b")).toHaveCount(0);
  await drawer.getByRole("button", { name: "Reply to conversation" }).click();
  await drawer.getByLabel("Write a reply").fill("Agreed — compare this with retention.");
  await drawer.getByRole("button", { name: "Reply", exact: true }).click();
  await expect(drawer.locator(".activity-reply")).toContainText("compare this with retention");
  await drawer.getByRole("button", { name: "Resolve", exact: true }).click();
  await expect(drawer.getByText("All caught up.")).toBeVisible();
  await drawer.getByLabel("Show resolved conversations").check();
  await drawer.getByRole("button", { name: "Reopen", exact: true }).click();
  await page.keyboard.press("Escape");
  await expect(drawer).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Chart comments, 1 open" })).toBeFocused();
  await page.getByRole("button", { name: /^Chart alerts/ }).first().click();
  await drawer.getByRole("button", { name: /Threshold Choose a clear boundary/ }).click();
  await drawer.getByLabel("Threshold (metric units)").fill("0");
  await drawer.getByRole("button", { name: "Preview check", exact: true }).click();
  await expect(drawer.getByText("Preview · nothing sent")).toBeVisible();
  await drawer.getByRole("button", { name: "Create alert", exact: true }).click();
  await expect(drawer.getByText("Watching for you", { exact: true })).toBeVisible();
  await expect(drawer.locator(".watch-event")).toHaveCount(1);
  await drawer.getByRole("button", { name: "Check now", exact: true }).click();
  await expect(drawer.locator(".watch-event")).toHaveCount(1);
  await drawer.getByRole("button", { name: "Mark all read" }).click();
  await expect(drawer.locator(".watch-event.unread")).toHaveCount(0);
  await drawer.getByRole("button", { name: "Edit alert", exact: true }).click();
  await drawer.getByRole("button", { name: /Unusual change Learn the recent pattern/ }).click();
  await drawer.getByRole("button", { name: "Preview check", exact: true }).click();
  await expect(drawer.getByRole("img", { name: /^Expected range/ })).toBeVisible();
  await drawer.getByRole("button", { name: "Update alert", exact: true }).click();
  await expect(drawer.getByRole("img", { name: /^Expected range/ })).toBeVisible();
  await drawer.getByRole("button", { name: "Pause", exact: true }).click();
  await expect(drawer.getByText("Paused", { exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Chart comments, 1 open" }).click();
  await expect(drawer.locator(".activity-reply")).toContainText("compare this with retention");
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(drawer).toBeVisible();
  expect(await drawer.evaluate(d => d.scrollWidth <= d.clientWidth)).toBe(true);
  await page.screenshot({ path: "test-results/activity-mobile.png" });
  await page.setViewportSize({ width: 1440, height: 950 });
  await page.screenshot({ path: "test-results/activity-comments-desktop.png" });
  await drawer.getByRole("tab", { name: /Alerts/ }).click();
  await expect(drawer.getByRole("tab", { name: /Alerts/ })).toHaveAttribute("aria-selected", "true");
  await expect(drawer.getByRole("img", { name: /^Expected range/ })).toBeVisible();
  await page.screenshot({ path: "test-results/activity-alert-desktop.png" });
  expect(errors).toEqual([]);
});
