import { openStarter } from "./library-helpers.ts";
import { expect, test } from "@playwright/test";

test("chart tools are opt-in, independent, and remembered across dashboards and reloads", async ({ page }) => {
  await page.goto("/");
  await page.getByLabel("Acting as", { exact: true }).selectOption("admin");
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  const chats = page.getByRole("switch", { name: "Chart chats", exact: true });
  const notifications = page.getByRole("switch", { name: "Chart notifications", exact: true });
  await expect(chats).not.toBeChecked();
  await expect(notifications).not.toBeChecked();
  await chats.focus(); await page.keyboard.press("Space");
  await expect(chats).toBeChecked();
  await page.getByRole("button", { name: "Done", exact: true }).click();
  await openStarter(page, "SaaS overview");
  const commentButtons = page.getByRole("button", { name: /^Chart comments/ });
  const alertButtons = page.getByRole("button", { name: /^Chart alerts/ });
  await expect(commentButtons.first()).toBeVisible();
  await expect(alertButtons).toHaveCount(0);
  await commentButtons.first().click();
  const discussion = page.getByRole("tab", { name: /Comments/ });
  await discussion.focus(); await page.keyboard.press("ArrowRight");
  await expect(discussion).toBeFocused();
  await expect(page.getByRole("tab", { name: /Alerts/ })).toHaveCount(0);
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Canvas settings", exact: true }).click();
  await page.getByRole("button", { name: "Chats & notifications" }).click();
  await chats.uncheck(); await notifications.check();
  await page.getByRole("button", { name: "Done", exact: true }).click();
  await expect(commentButtons).toHaveCount(0);
  await expect(alertButtons.first()).toBeVisible();
  await alertButtons.first().click();
  await expect(page.getByRole("tab", { name: /Comments/ })).toHaveCount(0);
  await expect(page.getByRole("tab", { name: /Alerts/ })).toBeVisible();
  await page.keyboard.press("Escape");
  await openStarter(page, "MRR movements");
  await expect(alertButtons.first()).toBeVisible();
  await expect(commentButtons).toHaveCount(0);
  await page.reload();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(chats).not.toBeChecked(); await expect(notifications).toBeChecked();
  await page.setViewportSize({ width: 390, height: 844 });
  const settings = page.getByRole("dialog", { name: "Settings", exact: true });
  expect(await settings.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.screenshot({ path: "test-results/chart-settings-mobile.png" });
  await notifications.uncheck();
  await page.getByRole("button", { name: "Done", exact: true }).click();
  await page.setViewportSize({ width: 1440, height: 950 });
  await openStarter(page, "SaaS overview");
  await expect(page.locator(".chart-activity-buttons")).toHaveCount(0);
});

test("chart preferences follow the local role and update an already open tab", async ({ page, context }) => {
  await page.goto("/");
  await page.getByLabel("Acting as", { exact: true }).selectOption("admin");
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await page.getByRole("switch", { name: "Chart chats", exact: true }).check();
  await page.getByRole("button", { name: "Done", exact: true }).click();
  const other = await context.newPage();
  await other.goto("/");
  await openStarter(other, "SaaS overview");
  await expect(other.getByRole("button", { name: /^Chart comments/ }).first()).toBeVisible();
  await other.getByRole("button", { name: /^Chart comments/ }).first().click();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await page.getByRole("switch", { name: "Chart chats", exact: true }).uncheck();
  await expect(other.getByRole("dialog")).toHaveCount(0);
  await expect(other.locator(".chart-activity-buttons")).toHaveCount(0);
  await page.getByRole("switch", { name: "Chart chats", exact: true }).check();
  await page.getByRole("button", { name: "Done", exact: true }).click();
  await page.getByLabel("Acting as", { exact: true }).selectOption("");
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(page.getByRole("switch", { name: "Chart chats", exact: true })).not.toBeChecked();
  await page.getByRole("button", { name: "Done", exact: true }).click();
  await page.getByLabel("Acting as", { exact: true }).selectOption("admin");
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(page.getByRole("switch", { name: "Chart chats", exact: true })).toBeChecked();
});
